<?php
/*
 * This file is part of the project tutteli/purchase published under the Apache License 2.0
 * For the full copyright and license information, please have a look at LICENSE in the
 * root folder or visit https://github.com/robstoll/purchase
 */

namespace Tutteli\AppBundle\Entity;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends \Doctrine\ORM\EntityRepository
{
    public function getLastUpdated() {
        $result = $this->getEntityManager()
            ->createQuery("SELECT u FROM TutteliAppBundle:User u ORDER BY u.updatedAt DESC")
            ->setMaxResults(1)
            ->getResult();
        if (count($result) > 0) {
            return $result[0];
        }
        return null;
    }
}
